version: '3.8'

services:
  database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: caestats
        MYSQL_USER: caestats
        MYSQL_PASSWORD: caestats
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/caestats
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/caestats
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
