name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: ${{ env.IMAGE_URL }}
